version: "3"
services:
  xxl-job:
    container_name: xxl-job
    image: xuxueli/xxl-job-admin:2.3.0
    ports:
      - "12000:8080"
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Xmx512m -Xms512m"
      PARAMS: "--spring.datasource.url=jdbc:mysql://19.50.79.5:3000/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=xxl-job --spring.datasource.password=vHWBxlcU --xxl.job.accessToken=AwkXJd3c"
    volumes:
      - "./logs:/data/applogs"