version: "3"
services:
  sentinel:
    container_name: redis-sentinel-2
    image: redis:6.0-alpine3.13
    ports:
      - "16379:6379"
    restart: always
    command: redis-sentinel /usr/local/etc/redis/redis-sentinel-1.conf
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./data/sentinel:/data"
      - "./conf:/usr/local/etc/redis"
    networks:
      - redis-slave-network
    sysctls:
      net.core.somaxconn: '511'
  slave:
    container_name: redis-slave-2
    image: redis:6.0-alpine3.13
    ports:
      - "6380:6379"
    restart: always
    command: redis-server /usr/local/etc/redis/redis-slave-1.conf
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./data/slave:/data"
      - "./conf:/usr/local/etc/redis"
    networks:
      - redis-slave-network
    sysctls:
      net.core.somaxconn: '511'
networks:
  redis-slave-network: