version: "3"
services:
  mysql-master:
    container_name: mysql-master-2
    image: ${MYSQL_VERSION}
    ports:
      - "3000:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./data/mysql-master-2:/var/lib/mysql"
      - "./slave.cnf:/etc/mysql/conf.d/slave.cnf"
    healthcheck:
      test: "mysql -uroot -p${MYSQL_ROOT_PASSWORD}"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mysql-master-network
networks:
  mysql-master-network: