version: "3"
services:
  sentinel:
    container_name: redis-sentinel-1
    image: redis:6.0-alpine3.13
    ports:
      - "16379:6379"
    restart: always
    command: redis-sentinel /usr/local/etc/redis/redis-sentinel-1.conf
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./data/sentinel:/data"
      - "./conf:/usr/local/etc/redis"
      - "./log:/var/log/redis"
    networks:
      - redis-master-network
    sysctls:
      net.core.somaxconn: '511'
    depends_on:
      - master
  master:
    container_name: redis-master
    image: redis:6.0-alpine3.13
    ports:
      - "6379:6379"
    restart: always
    command: redis-server /usr/local/etc/redis/redis-master.conf
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./data/master:/data"
      - "./conf:/usr/local/etc/redis"
    networks:
      - redis-master-network
    sysctls:
      net.core.somaxconn: '511'
  slave:
    container_name: redis-slave-1
    image: redis:6.0-alpine3.13
    ports:
      - "6380:6379"
    restart: always
    command: redis-server /usr/local/etc/redis/redis-slave-1.conf
    environment:
      TZ: "Asia/Shanghai"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - "./data/slave:/data"
      - "./conf:/usr/local/etc/redis"
    networks:
      - redis-master-network
    depends_on:
      - master
networks:
  redis-master-network: