version: "3"
services:
  master:
    container_name: keep-alived-master
    image: arcts/keepalived:1.2.2
    restart: always
    environment:
      KEEPALIVED_AUTOCONF: "false"
    volumes:
      - "./data:/root"
      - "./conf/keepalived-m2.conf:/etc/keepalived/keepalived.conf"
    cap_add:
      - NET_ADMIN
    network_mode: "host"