version: "3"
services:
  nacos:
    container_name: nacos-cluster
    image: nacos/nacos-server:${NACOS_VERSION}
    volumes:
      - ./data/cluster-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
      - "7848:7848"
    env_file:
      - ./env/nacos-ip.env
    restart: always