version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./logs:/var/log/nginx"
      - "./html:/usr/share/nginx/html:ro"