version: '3'
services:
  sentinel-dashboard:
    image: sentinel-dashboard-cloud
    container_name: sentinel-dashboard
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8719 -Xms1g -Xmx1g -Dauth.password=meO2VwQlBjPPo4R5
    volumes:
      - ./log/sentinel-dashboard:/root/logs/csp

